### ISSUE TITLE
Can't access updated mapStateToProps object in validator method

### ISSUE THREAD

**Issue by Chris7721** [saini-g/react-step-progress#16]
When the validator method is run, it still holds the previous redux state, it doesn't get the updated object.

**Comment by jordaofabio** [comment]
I have the same problem, right now! :/

**Comment by Chris7721** [comment]
> I have the same problem, right now! :/

I had to reach out to local storage for the validation and interestingly, it worked.

**Comment by jordaofabio** [comment]
> > I have the same problem, right now! :/
> 
> I had to reach out to local storage for the validation and interestingly, it worked.

Yes, I did it too. I thought to try do the steps by myself, but it would have some hours...

Thanks!
